sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
before_script:
- pip install -e .
- pip install pep8
- pip install coverage
- pip install python-coveralls
- cp travis-ci/manage.py manage.py
script:
- pep8 blti/
- coverage run --source=blti manage.py test blti
after_success:
- coveralls
before_deploy:
- find blti/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > blti/VERSION
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure:
  on:
    tags: true
    python: '3.5'
