sudo: false
language: python
python:
  - "2.7"
  - "3.6"
before_install:
    - cp travis-ci/test_requirements.txt requirements.txt
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
script:
  - pep8 blti/
  - coverage run --source=blti manage.py test blti
after_script:
  - coveralls
